import numpy as np
import pandas as pd

def load_pos_bonsai(path, ppm):
    """
    Load position data from a .csv file generated by Bonsai
    Assumes columns are structured as follows:
    -

    CURRENTLY ASSUMES TWO LEDs ARE BEING TRACKED
    Required columns: Item2.X, Item2.Y, Item3.X, Item3.Y

    Parameters
    ----------
    path : str
        Path to the .csv file to be loaded
    ppm : int, optional
        Pixels per metre for scaling

    """

    # Read position data from csv file
    data = pd.read_csv(f'{path}/bonsai.csv', index_col = 0)

    pos_header = {'pixels_per_metre': ppm}

    # Extract LED position data and tracked pixel size data
    led_pos = data.loc[:, ['Item2.X', 'Item2.Y', 'Item3.X', 'Item3.Y']].T

    #Scale pos data to specific PPM
    real_ppm = ppm
    goal_ppm = 400 #HARD CODED FOR NOW
    pos_header['scaled_ppm'] = goal_ppm
    scale_fact = goal_ppm / real_ppm

    # Scale pos data in place
    led_pos *= scale_fact

    raw_pos_data = {'header': pos_header,
                    'led_pos': led_pos}

    return raw_pos_data
